#!/usr/bin/python3
# -*- coding: utf-8 -*-
import os
import sys
import time
import json

import requests
from bs4 import BeautifulSoup
from mastodon import Mastodon

rc = os.environ.get('HOME', '.') + '/.dqxpresence'
pr = os.environ.get('HOME', '.') + '/.mpresence'


class DQX:
    def __init__(self):
        j = {}
        self.pre_status = ''
        with open(rc) as f:
            j = json.loads(f.read())
        try:
            with open(pr) as f:
                self.pre_status = f.read().strip()
        except Exception:
            self.writePresence('')

        self.client = j.get('mastodon_client')
        self.secret = j.get('mastodon_secret')
        self.token = j.get('mastodon_token')
        self.instance = j.get('mastodon_instance')
        self.user_id = j.get('id')
        self.namebase = j.get('namebase')

        if self.client and self.secret and self.token and self.instance:
            self.mstdn = Mastodon(client_id=self.client,
                                  client_secret=self.secret,
                                  access_token=self.token,
                                  api_base_url=self.instance)

    def writePresence(self, status):
        with open(pr, 'w') as f:
            f.write(status)

    def getStatus(self):
        r = requests.get(f'http://hiroba.dqx.jp/sc/character/{self.user_id}/status', timeout=10)
        if r and r.status_code == 200:
            soup = BeautifulSoup(r.content, 'html.parser')
            level = soup.find('td', class_='text-center').text
            level = level.strip('\t\r\n')
            level = level.replace(u'\xa0', '')
            level = level.replace('/レベル', '')
            return level
        return ''

    def setDisplayName(self, display_name):
        self.mstdn.account_update_credentials(display_name=display_name)

    def toot(self):
        if not sys.stdin.isatty():
            text = sys.stdin.read().strip()
            if text:
                self.mstdn.status_post(text)


if __name__ == '__main__':
    dqx = DQX()

    if len(sys.argv) > 1:
        cmd = sys.argv[1]
        if cmd == 'reset':
            st = os.stat(pr)
            if time.time() - st.st_mtime >= 3600:
                dqx.setDisplayName(f'{dqx.namebase}')
        if cmd == 'toot':
            dqx.toot()
        exit()

    status = dqx.getStatus()
    if status == dqx.pre_status:
        exit()

    if dqx.namebase:
        dqx.writePresence(status)
        dqx.setDisplayName(f'{dqx.namebase}＠{dqx.status}')
